project:
  type: website
  execute-dir: project
  output-dir: docs

format:
  html:
    theme:
      - solar
      - html/custom.scss
    css:
      # - html/styles.css
      - html/webex.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    include-after-body:
      - text: |
          <script src="/js/bootstrapify.js"></script>
          <script src="/js/webex.js"></script>

execute:
  cache: false
  freeze: false

engine: knitr

knitr:
  opts_chunk:
    message: false
    warning: false
    fig-align: center

webr:
  channel-type: "post-message"
  autoload-packages: false

custom-callout:
  practice:
    title: "Practice"
    icon-symbol: "fa-gears"
    color: "green"
  knowledge-check:
    title: "Knowledge Check"
    icon-symbol: "fa-pen-to-square"
    color: "#368FFF"
  reading:
    title: "Reading"
    icon-symbol: "fa-book-open"
    color: "violet"
  reading-advanced:
    title: "Advanced Reading"
    icon-symbol: "fa-book-open"
    color: "red"
  resource:
    title: "External Resources"
    icon-symbol: "fa-link"
    color: "orange"
  common-mistakes:
    title: "Common Mistakes"
    icon-symbol: "fa-bug"
    color: "#B01919"
  going-further:
    title: "Going Further"
    icon-symbol: "fa-route"
    color: "#B58900"
  completion-time:
    title: "Estimated Completion Time"
    icon-symbol: "fa-stopwatch"
    color: "gray"
  explanation:
    title: "Explanation"
    icon-symbol: "fa-comment"
    color: "violet"
    collapse: true

filters:
  - webr
  - custom-callout

## Import the website metadata since that section gets pretty complicated
metadata-files:
  - _website.yml
