---
title: "R Packages"
---

## Why Packages?

You've now learned how to use dozens of R's built-in functions, such as `mean()`, `round()`, `sqrt()`, `sum()`, and many
more. These all ship with R itself, ready to use the moment you start an R session. But R's built-in functions can't
cover every possible task. Fortunately, for most specialized tasks that you'll need to do work-a-day data analysis
(e.g., fitting advanced statistical models, reading data from unusual file formats, making fancy plots), someone in the
R community has written and shared the necessary routines. These community-contributed routines are distributed in
pre-build software bundles called *R Packages*.

## What Is a Package?

A **package** is simply a collection of functions and documentation (i.e., help files) that some enterprising citizen
has written, bundled, and distributed for you and me to use. The functions provided by R packages work in exactly the
same way as the Base R functions you learned about in the [**R Functions**](https://openstatprog.com/functions/) module.
So, you don't need to do anything special when using functions provided by packages.

The following list shows a few common data-analysis tasks and some packages that provide relevant functions for each.

- Treating missing data using multiple imputation
	- [mice](https://cran.r-project.org/web/packages/mice/index.html)
	- [Amelia](https://cran.r-project.org/web/packages/Amelia/index.html)
	- [mi](https://cran.r-project.org/web/packages/mi/index.html)
- Structural equation modeling
	- [lavaan](https://cran.r-project.org/web/packages/lavaan/index.html)
	- [OpenMx](https://cran.r-project.org/web/packages/OpenMx/index.html)
- Multilevel regression modeling
	- [lme4](https://cran.r-project.org/web/packages/lme4/index.html)
	- [nlme](https://cran.r-project.org/web/packages/nlme/index.html)
- For all but the most trivial data processing, manipulation, and visualization, the
[tidyverse](https://www.tidyverse.org/) packages are virtually obligatory.

Since package-provided functions behave in the same way as R's core functions, there are only two special things you
need to consider when using packages.

1. How to **install** a new package (which you only do once)
1. How to **load** an installed package (which you must do every time you want to use the package in a new R session)

The rest of this tutorial is dedicated to these two topics.

::: knowledge-check

In your own words, explain the difference between a function and a package.

:::
